### PR TITLE
Deckbuilding refine

### PR DESCRIPTION
**Pull request by rymTooo**
Refined Deckbuilding
- add card filtering
- add card sorting
- add card information on available cards display
- fix card.json format ( effect from dict to list of dict )

Note that there are some mismatch between Card image and name on some card. Maybe the sprite coordinate is wrong. 
And there used to be  some bugs which I have no idea how to recreate. Try moving and clicking and see if there any bug.

Note2 I make "card2.json" for the fix format, if you want to try the old one, change the file location in Util.py to "card.json"

### CODE REVIEW

**Review by phukaokub — COMMENTED** [review]
There are some Effect Type filters doesn't work properly by not showing any cards after select e.g. attack, self_buff, range_buff. May be the effect is not implemented? Then nothing has to changed and can merge.

**Review by phukaokub — CHANGES_REQUESTED** [review]
I think the bug you are having issue with comes from the filter function. That some time when we press filter button it said Index out of range. Maybe you manipulate the self.availableCard and didn't handle it properly by save the instance or copy it.

**Comment by rymTooo** [comment]
> There are some Effect Type filters doesn't work properly by not showing any cards after select e.g. attack, self_buff, range_buff. May be the effect is not implemented? Then nothing has to changed and can merge.

it is a given since this is the original effect type that exist in Enum variable but not exist in this version of card effect type

**Comment by rymTooo** [comment]
> I think the bug you are having issue with comes from the filter function. That some time when we press filter button it said Index out of range. Maybe you manipulate the self.availableCard and didn't handle it properly by save the instance or copy it.

how to recreate the bug please? what did you click?

**Comment by rymTooo** [comment]
fixed ^^

**Review by krittintrs — APPROVED** [review]

**Review by phukaokub — APPROVED** [review]

**Pull request merged**
