### PR TITLE
Implement Buff Card & Warrior Card

### PR DESCRIPTION
**Pull request by krittintrs**
- Implement buff card (C18-21, C23-29)
- Implement warrior card (C38, C40-C42)
- Refactor JSON format & load function in util.py
- Implement buff config for buff card
- Implement function to retrieve buffs from effect & apply to entity
- Refactor effect types format
  - `ATTACK`: choose tile to attack
  - `MOVE`: choose tile to move
  - `SELF_BUFF`: apply buff to yourself
  - `OPPO_BUFF`: choose tile to apply buff to opponent
  - `ATTACK_SELF_BUFF`: choose tile to attack -> if hit, then apply buff to yourself
  - `ATTACK_OPPO_BUFF`: choose tile to attack -> if hit, then apply buff to opponent

### CODE REVIEW

**Review by phukaokub — APPROVED** [review]
👍

**Comment by phukaokub** [comment]
image
For the Buff display maybe we change the buff name to actual status buff.

**Comment by phukaokub** [comment]
image
Is this legit? the opponent show buff with 0 turn

**Review by Patharapol1573 — APPROVED** [review]

**Comment by krittintrs** [comment]
> image Is this legit? the opponent show buff with 0 turn

not sure why, will recheck the duration logic again

**Review by phukaokub — CHANGES_REQUESTED** [review]
image
Bug with opponent dice roll buff. It appears they have 2 buffs.

**Comment by phukaokub** [comment]
I think this should be new Issue, where the buff increased the attack and defense of the card which will not perform those action.
image

**Comment by krittintrs** [comment]
> image Bug with opponent dice roll buff. It appears they got 2 buffs.

This never happens to me, can you debug it to identify the potential flaw in the code?

**Comment by krittintrs** [comment]
> image For the Buff display maybe we change the buff name to actual status buff.

done kub

**Comment by phukaokub** [comment]
> > image For the Buff display maybe we change the buff name to actual status buff.
> 
> done kub

Do you gonna change the buff bugged for enemy dice roll buff?

**Comment by krittintrs** [comment]
> roll

As I said before, this situation never happens to me, so I cannot fix or discover the flaw. Can you debug to identify the potential flaw in the code?

**Comment by krittintrs** [comment]
> > > image For the Buff display maybe we change the buff name to actual status buff.
> 
> > 
> 
> > done kub
> 
> 
> 
> Do you gonna change the buff bugged for enemy dice roll buff?

As I said before, this situation never happens to me, so I cannot fix or discover the flaw. Can you debug to identify the potential flaw in the code?

**Review by phukaokub — APPROVED** [review]

**Review by rymTooo — APPROVED** [review]
👍

**Pull request merged**
